services:
  - type: web
    name: kuis-pengetahuan-v1
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Kuis Cakrawala
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        value: ""
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: RUN_MIGRATIONS
        value: "true"
      - key: RUN_DB_SEED
        value: "false"
